<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MarchePublic;

class MarchePublicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        MarchePublic::create([
            'type_ao'              => 'Etudes',
            'n_reference'          => '01/2025',
            'etat'                 => null,
            'is_accepted'          => false,
            'etape'                => null,
            'date_limite'          => '2025-11-15',
            'heure'                => '10:00:00',
            'mo'                   => 'Commune de Casablanca',
            'objet'                => 'Étude de faisabilité pour l\'aménagement d\'un complexe sportif municipal',
            'estimation'           => 350000,
            'caution'              => 7000,
            'attestation_reference'=> 'OUI',
            'cnss'                 => 'OUI',
            'agrement'             => null,
            'equipe_demandee'      => "Architecte - exp 10 ans\nIngénieur structure - exp 8 ans\nTechnicien BTP - exp 5 ans",
            'contrainte'           => 'Respect des normes environnementales',
            'autres'               => 'Attestation de capacité technique requise',
            'mode_attribution'     => '65% technique + 35% financier',
            'lieu_ao'              => 'https://www.marchespublics.gov.ma/index.php?page=entreprise.EntrepriseDetailsConsultation&refConsultation=100001&orgAcronyme=cas',
            'ville'                => 'Casablanca',
            'lots'                 => null,
            'decision'             => null,
            'date_decision'        => null,
            'ordre_preparation'    => null,
            'importance'           => 'ao_ouvert',
        ]);

        MarchePublic::create([
            'type_ao'              => 'Fournitures',
            'n_reference'          => '02/2025',
            'etat'                 => null,
            'is_accepted'          => false,
            'etape'                => null,
            'date_limite'          => '2025-12-08',
            'heure'                => '14:30:00',
            'mo'                   => 'Hôpital Régional de Fès',
            'objet'                => 'Fourniture d\'équipements médicaux pour le service de cardiologie',
            'estimation'           => 890000,
            'caution'              => 17800,
            'attestation_reference'=> 'OUI',
            'cnss'                 => 'OUI',
            'agrement'             => 'Qualification médicale',
            'equipe_demandee'      => "Technicien biomédical - exp 5 ans\nIngénieur maintenance - exp 7 ans",
            'contrainte'           => 'Certification ISO 13485 obligatoire',
            'autres'               => 'Garantie 3 ans minimum',
            'mode_attribution'     => 'Moins disant + critères techniques',
            'lieu_ao'              => 'https://www.marchespublics.gov.ma/index.php?page=entreprise.EntrepriseDetailsConsultation&refConsultation=200002&orgAcronyme=fes',
            'ville'                => 'Fès',
            'lots'                 => 'Lot 1: Moniteurs - Lot 2: Défibrillateurs',
            'decision'             => null,
            'date_decision'        => null,
            'ordre_preparation'    => null,
            'importance'           => 'ao_important',
        ]);

        MarchePublic::create([
            'type_ao'              => 'Travaux',
            'n_reference'          => '03/2025',
            'etat'                 => null,
            'is_accepted'          => false,
            'etape'                => null,
            'date_limite'          => '2025-11-25',
            'heure'                => '11:00:00',
            'mo'                   => 'Office National de l\'Électricité et de l\'Eau Potable',
            'objet'                => 'Extension du réseau d\'assainissement dans la zone industrielle de Tanger',
            'estimation'           => 2500000,
            'caution'              => 50000,
            'attestation_reference'=> 'OUI',
            'cnss'                 => 'OUI',
            'agrement'             => 'Catégorie 1 - Assainissement',
            'equipe_demandee'      => "Ingénieur hydraulique - exp 15 ans\nChef de projet - exp 10 ans\nContrôleur qualité - exp 8 ans",
            'contrainte'           => 'Travaux de nuit autorisés uniquement',
            'autres'               => 'Plan de circulation obligatoire',
            'mode_attribution'     => '70% technique + 30% prix',
            'lieu_ao'              => 'https://www.marchespublics.gov.ma/index.php?page=entreprise.EntrepriseDetailsConsultation&refConsultation=300003&orgAcronyme=onee',
            'ville'                => 'Tanger',
            'lots'                 => null,
            'decision'             => null,
            'date_decision'        => null,
            'ordre_preparation'    => null,
            'importance'           => 'ao_simplifie',
        ]);

        MarchePublic::create([
            'type_ao'              => 'Services',
            'n_reference'          => '04/2025',
            'etat'                 => null,
            'is_accepted'          => false,
            'etape'                => null,
            'date_limite'          => '2025-10-30',
            'heure'                => '09:00:00',
            'mo'                   => 'Université Mohammed V - Rabat',
            'objet'                => 'Services de maintenance informatique et réseau pour 3 ans',
            'estimation'           => 450000,
            'caution'              => 9000,
            'attestation_reference'=> 'OUI',
            'cnss'                 => 'OUI',
            'agrement'             => null,
            'equipe_demandee'      => "Ingénieur réseau - exp 5 ans\nTechnicien informatique - exp 3 ans",
            'contrainte'           => 'Disponibilité 24h/24 - 7j/7',
            'autres'               => 'Certification Cisco ou équivalent',
            'mode_attribution'     => '50% technique + 50% prix',
            'lieu_ao'              => 'https://www.marchespublics.gov.ma/index.php?page=entreprise.EntrepriseDetailsConsultation&refConsultation=400004&orgAcronyme=um5',
            'ville'                => 'Rabat',
            'lots'                 => null,
            'decision'             => null,
            'date_decision'        => null,
            'ordre_preparation'    => null,
            'importance'           => 'ao_restreint',
        ]);

        MarchePublic::create([
            'type_ao'              => 'Etudes',
            'n_reference'          => '05/2025',
            'etat'                 => null,
            'is_accepted'          => false,
            'etape'                => null,
            'date_limite'          => '2025-12-20',
            'heure'                => '15:00:00',
            'mo'                   => 'Agence Urbaine de Meknès',
            'objet'                => 'Étude d\'impact environnemental pour un projet résidentiel',
            'estimation'           => 180000,
            'caution'              => 3600,
            'attestation_reference'=> 'OUI',
            'cnss'                 => 'OUI',
            'agrement'             => 'Agrément environnement',
            'equipe_demandee'      => "Expert environnementaliste - exp 12 ans\nHydrogéologue - exp 8 ans",
            'contrainte'           => null,
            'autres'               => 'Rapport en français et arabe',
            'mode_attribution'     => '80% technique + 20% prix',
            'lieu_ao'              => 'https://www.marchespublics.gov.ma/index.php?page=entreprise.EntrepriseDetailsConsultation&refConsultation=500005&orgAcronyme=aum',
            'ville'                => 'Meknès',
            'lots'                 => null,
            'decision'             => null,
            'date_decision'        => null,
            'ordre_preparation'    => null,
            'importance'           => 'ao_preselection',
        ]);

        MarchePublic::create([
            'type_ao'              => 'Travaux',
            'n_reference'          => '06/2025',
            'etat'                 => null,
            'is_accepted'          => false,
            'etape'                => null,
            'date_limite'          => '2025-11-10',
            'heure'                => '16:30:00',
            'mo'                   => 'Direction Provinciale de l\'Équipement - Oujda',
            'objet'                => 'Construction d\'un pont sur Oued Moulouya',
            'estimation'           => 3200000,
            'caution'              => 64000,
            'attestation_reference'=> 'OUI',
            'cnss'                 => 'OUI',
            'agrement'             => 'Catégorie 1 - Ouvrages d\'art',
            'equipe_demandee'      => "Ingénieur ponts et chaussées - exp 20 ans\nIngénieur béton armé - exp 15 ans\nChef de chantier - exp 12 ans",
            'contrainte'           => 'Respect du débit de l\'oued en période de crue',
            'autres'               => 'Étude géotechnique préalable fournie',
            'mode_attribution'     => '75% technique + 25% prix',
            'lieu_ao'              => 'https://www.marchespublics.gov.ma/index.php?page=entreprise.EntrepriseDetailsConsultation&refConsultation=600006&orgAcronyme=dpe',
            'ville'                => 'Oujda',
            'lots'                 => null,
            'decision'             => null,
            'date_decision'        => null,
            'ordre_preparation'    => null,
            'importance'           => 'ao_bon_commande',
        ]);

        MarchePublic::create([
            'type_ao'              => 'Fournitures',
            'n_reference'          => '07/2025',
            'etat'                 => null,
            'is_accepted'          => false,
            'etape'                => null,
            'date_limite'          => '2025-10-15',
            'heure'                => '10:30:00',
            'mo'                   => 'Académie Régionale de l\'Éducation - Marrakech',
            'objet'                => 'Acquisition de mobilier scolaire pour 50 établissements',
            'estimation'           => 680000,
            'caution'              => 13600,
            'attestation_reference'=> 'OUI',
            'cnss'                 => 'OUI',
            'agrement'             => null,
            'equipe_demandee'      => "Responsable qualité - exp 5 ans",
            'contrainte'           => 'Livraison avant la rentrée scolaire',
            'autres'               => 'Garantie 2 ans sur le mobilier',
            'mode_attribution'     => 'Moins disant conforme',
            'lieu_ao'              => 'https://www.marchespublics.gov.ma/index.php?page=entreprise.EntrepriseDetailsConsultation&refConsultation=700007&orgAcronyme=are',
            'ville'                => 'Marrakech',
            'lots'                 => 'Lot 1: Tables - Lot 2: Chaises - Lot 3: Tableaux',
            'decision'             => null,
            'date_decision'        => null,
            'ordre_preparation'    => null,
            'importance'           => 'ao_ouvert',
        ]);

        MarchePublic::create([
            'type_ao'              => 'Services',
            'n_reference'          => '08/2025',
            'etat'                 => null,
            'is_accepted'          => false,
            'etape'                => null,
            'date_limite'          => '2025-12-05',
            'heure'                => '13:00:00',
            'mo'                   => 'Commune de Tétouan',
            'objet'                => 'Service de collecte et traitement des déchets ménagers',
            'estimation'           => 1100000,
            'caution'              => 22000,
            'attestation_reference'=> 'OUI',
            'cnss'                 => 'OUI',
            'agrement'             => 'Autorisation déchets',
            'equipe_demandee'      => "Ingénieur environnement - exp 8 ans\nChef d\'exploitation - exp 10 ans",
            'contrainte'           => 'Collecte 6 jours sur 7',
            'autres'               => 'Véhicules conformes aux normes Euro 6',
            'mode_attribution'     => '60% technique + 40% prix',
            'lieu_ao'              => 'https://www.marchespublics.gov.ma/index.php?page=entreprise.EntrepriseDetailsConsultation&refConsultation=800008&orgAcronyme=tet',
            'ville'                => 'Tétouan',
            'lots'                 => null,
            'decision'             => null,
            'date_decision'        => null,
            'ordre_preparation'    => null,
            'importance'           => 'ao_important',
        ]);

        MarchePublic::create([
            'type_ao'              => 'Travaux',
            'n_reference'          => '09/2025',
            'etat'                 => null,
            'is_accepted'          => false,
            'etape'                => null,
            'date_limite'          => '2025-11-28',
            'heure'                => '11:30:00',
            'mo'                   => 'Office National des Chemins de Fer',
            'objet'                => 'Modernisation de la signalisation ferroviaire Rabat-Casablanca',
            'estimation'           => 4500000,
            'caution'              => 90000,
            'attestation_reference'=> 'OUI',
            'cnss'                 => 'OUI',
            'agrement'             => 'Qualification ferroviaire',
            'equipe_demandee'      => "Ingénieur signalisation - exp 15 ans\nTechnicien électronique - exp 10 ans\nChef de projet ferroviaire - exp 12 ans",
            'contrainte'           => 'Travaux en dehors des heures de circulation',
            'autres'               => 'Certification sécurité ferroviaire obligatoire',
            'mode_attribution'     => '85% technique + 15% prix',
            'lieu_ao'              => 'https://www.marchespublics.gov.ma/index.php?page=entreprise.EntrepriseDetailsConsultation&refConsultation=900009&orgAcronyme=oncf',
            'ville'                => 'Rabat',
            'lots'                 => 'Lot 1: Rabat-Salé - Lot 2: Salé-Casablanca',
            'decision'             => null,
            'date_decision'        => null,
            'ordre_preparation'    => null,
            'importance'           => 'ao_simplifie',
        ]);

        MarchePublic::create([
            'type_ao'              => 'Etudes',
            'n_reference'          => '10/2025',
            'etat'                 => null,
            'is_accepted'          => false,
            'etape'                => null,
            'date_limite'          => '2025-12-15',
            'heure'                => '14:00:00',
            'mo'                   => 'Agence du Bassin Hydraulique du Souss-Massa',
            'objet'                => 'Étude hydrologique pour la gestion des ressources en eau',
            'estimation'           => 720000,
            'caution'              => 14400,
            'attestation_reference'=> 'OUI',
            'cnss'                 => 'OUI',
            'agrement'             => 'Agrément hydraulique',
            'equipe_demandee'      => "Hydrologue - exp 15 ans\nIngénieur géologue - exp 10 ans\nTechnicien hydrométrie - exp 8 ans",
            'contrainte'           => 'Campagne de mesures sur 12 mois',
            'autres'               => 'Matériel de mesure certifié requis',
            'mode_attribution'     => '75% technique + 25% prix',
            'lieu_ao'              => 'https://www.marchespublics.gov.ma/index.php?page=entreprise.EntrepriseDetailsConsultation&refConsultation=100010&orgAcronyme=abhsm',
            'ville'                => 'Agadir',
            'lots'                 => null,
            'decision'             => null,
            'date_decision'        => null,
            'ordre_preparation'    => null,
            'importance'           => null,
        ]);
    }
}