<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('logiciels', function (Blueprint $table) {
            $table->id(); // Auto-incrementing primary key
            $table->string('name'); // Name of the logiciel
            $table->string('domaine'); // Domain of the logiciel (e.g. Development, Design)
            $table->text('description'); // Description of the logiciel
            $table->string('output'); // Output generated by the logiciel (e.g. file types, reports)
            $table->enum('statut', ['free', 'crack', 'license']); // Statut of the logiciel
            $table->timestamps(); // created_at and updated_at timestamps
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('logiciels');
    }
};
